### ISSUE TITLE
ReferenceError: Logger is not defined

### ISSUE THREAD

**Issue by Peque** [dubstar-04/Design#234] opened 2023-10-17 21:30 UTC
The current version available in Flatpak seems to be unable to open [this file](https://github.com/dubstar-04/Design/files/12961869/plan.txt)  (note you'll need to rename the extension from `.txt` to `.dxf`):

![image](https://github.com/dubstar-04/Design/assets/526577/6cbc3705-5bcd-46e9-9419-ad8fe7adbc91)

@dubstar-04 Can you reproduce it?

**Comment by dubstar-04** [comment] 2023-12-30 12:31
I can't reproduce the exact error. I get a different error about invalid line types. Thank you for supplying the file and reporting the issue.

**Comment by Peque** [comment] 2023-12-30 12:44
In case it helps, I installed the latest Flatpak package from Flathub using Fedora 39. I guess the OS should not matter, but just in case there is some reference not properly set an using some OS Logger instead of the one that should be available in the runtime.

**Comment by dubstar-04** [comment] 2024-01-07 12:44
Thanks for reporting this issue. 

I think it is now fixed:

![image](https://github.com/dubstar-04/Design/assets/1136710/98756a3f-7cfc-4947-83d2-2d6ff09837b1)

**Closed by dubstar-04** 2024-01-07 12:44 UTC

**Comment by dubstar-04** [comment] 2024-01-07 15:31
> Thanks @dubstar-04 . The same error persists. 🤷

Are you building a flatpak from main?

**Comment by Peque** [comment] 2024-01-07 15:34
@dubstar-04 No; just used the latest Flatpak version available in Flathub. I have just noticed the app has not been updated there yet, so you can ignore my comment. I will re-test once there is an update in Flathub. :blush:

**Comment by dubstar-04** [comment] 2024-01-07 15:49
Phew!

**Comment by Peque** [comment] 2024-06-07 08:23
Fixed after latest Flatpak upgrade. :rocket: :blush:
